stages:
 - etapa1 
 - Etapa2
 - etapa3

Etapa1:
  stage: etapa1
  when: on_success
  script:
    - echo "etapa 1"

Etapa2:
  stage: etapa2
  when: on_failure
  script:
    - echo "etapa 2"

Etapa3:
  stage: etapa2
  when: always
  script:
    - echo "sempre será executado"